---
title: ""
format:
  html:
    toc: false
---

## Transforming Food Systems for a Rising India

[Read the book (Open Access) →](https://link.springer.com/book/10.1007/978-3-030-14409-8){target="_blank"}

Over the last decade, increases in per capita incomes, greater urbanization rates, increase in literacy rates, population growth and poverty reduction has characterized this high growth process. Yet, in a small farm dominant country like India, poor infrastructure and a lack of institutional support has excluded many small holders from benefiting from the growth process. At the macro level, the growth process has been highly inequitable benefiting some states more than others. At the consumer end, increases in income and income generating opportunities continue to coexist with poor health outcomes.

**Key Questions:**

1. How can India move towards the SDGs -- zero malnutrition and poverty?
2. What are the ways to re-organize the production systems to feed a nutritious diet for the growing population, while ensuring sustainable agriculture systems?
3. Can we come up with newer ways to ensure that economic growth stimulates the rural economy through providing more livelihood opportunities?
4. Are there ways to ensure greater equity in regional growth across the country while still guiding the Indian economy towards greater structural transformation?
