---
title: ""
format:
  html:
    toc: true
---

## Media Coverage

**The Economist** - [Even as India urbanises, caste discrimination remains rife](https://www.economist.com/asia/2020/07/23/even-as-india-urbanises-caste-discrimination-remains-rife) (July 2020)

**The Hindu** - [Study reveals caste-based segregation in Bengaluru](https://www.thehindu.com/news/cities/bangalore/study-reveals-caste-based-segregation-in-bengaluru/article26039905.ece)

**The Print** - [Segregation in rural Karnataka greater than local black-white division in US South: Study](https://theprint.in/opinion/segregation-in-rural-karnataka-greater-than-local-black-white-division-in-us-south-study/550596/)

**Scroll** - [What is the extent of caste segregation in Indian villages today? New data gives us an idea](https://scroll.in/article/979318/what-is-the-extent-of-caste-segregation-in-indian-villages-today-new-data-gives-us-an-idea)

**Newsclick** - [Myth of caste-free metropolises](https://newsclick.in/myth-caste-free-metropolises)

**The New Indian Express** - [Caste segregation still prevalent in cities: Study](https://www.newindianexpress.com/states/karnataka/2018/jul/22/caste-segregation-still-prevalent-in-cities-study-1846824.html)

## Non-technical Summaries

**Ideas for India:**
- [Residential segregation in urban India and persistence of caste inequality](https://www.ideasforindia.in/topics/urbanisation/residential-segregation-in-urban-india-and-persistence-of-caste-i.html)
- [Diversity and public goods: Why the geographical unit of analysis matters](https://www.ideasforindia.in/topics/governance/diversity-and-public-goods-why-the-geographical-unit-of-analysis-matters.html)

**India in Transition (CASI):**
- [A Permanent Cordon Sanitaire: Intra-Village Spatial Segregation and Social Distance in India](https://casi.sas.upenn.edu/iit/bharathi-malghan-rahman)